project_name: chainlink-devspace

version: 2

env:
  - IMAGE_LABEL_DESCRIPTION="node of the decentralized oracle network, bridging on and off-chain computation"
  - ZIG_EXEC={{ if index .Env "ZIG_EXEC"  }}{{ .Env.ZIG_EXEC }}{{ else }}zig{{ end }}
  - IMAGE_LABEL_LICENSES="MIT"
  - IMAGE_LABEL_SOURCE="https://github.com/smartcontractkit/{{ .ProjectName }}"

before:
  hooks:
    - go mod tidy
    - ./tools/bin/goreleaser_utils_arm before_hook

# See https://goreleaser.com/customization/build/
builds:
  - binary: chainlink
    id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      post: ./tools/bin/goreleaser_utils build_post_hook {{ dir .Path }} {{ .Os }} {{ .Arch }}
    flags:
      - -trimpath
      - -buildmode=pie
    env:
      - CGO_ENABLED=1
      - CC=$ZIG_EXEC cc -target aarch64-linux-gnu
      - CCX=$ZIG_EXEC c++ -target aarch64-linux-gnu
    ldflags:
      - -s -w -r=$ORIGIN/libs
      - -X github.com/smartcontractkit/chainlink/v2/core/static.Version={{ .Env.CHAINLINK_VERSION }}
      - -X github.com/smartcontractkit/chainlink/v2/core/static.Sha={{ .FullCommit }}

# See https://goreleaser.com/customization/docker/
dockers:
  - id: linux-arm64
    dockerfile: core/chainlink.goreleaser.Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    extra_files:
      - tmp/linux_arm64/libs
      - tmp/linux_arm64/plugins
      - tools/bin/ldd_fix
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--build-arg=CHAINLINK_USER=chainlink"
      - "--build-arg=COMMIT_SHA={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.description={{ .Env.IMAGE_LABEL_DESCRIPTION }}"
      - "--label=org.opencontainers.image.licenses={{ .Env.IMAGE_LABEL_LICENSES }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .Env.IMAGE_LABEL_SOURCE }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Env.CHAINLINK_VERSION }}"
      - "--label=org.opencontainers.image.url={{ .Env.IMAGE_LABEL_SOURCE }}"
    image_templates:
      - "{{ .Env.IMAGE }}"
# See https://goreleaser.com/customization/docker_manifest/
docker_manifests:
  - name_template: "{{ .Env.IMAGE }}"
    image_templates:
      - "{{ .Env.IMAGE }}"

archives:
  - format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: '{{ .Env.CHAINLINK_VERSION }}-{{ .Runtime.Goarch }}-{{ .Now.Format "2006-01-02-15-04-05Z" }}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
