[Network]
selected_networks = ["BASE_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 0.2

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "10m"

[Soak.OCR.Soak]
time_between_rounds = "2m"

[OCR.Common]
number_of_contracts = 2
