[Network]
selected_networks = ["CELO_ALFAJORES"]

[Soak.Common]
chainlink_node_funding = 5

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "72h"

[Soak.OCR.Soak]
time_between_rounds = "5m"

[OCR.Common]
number_of_contracts = 2
