name: "Filter Changes"
description: "Filters changed files based on 'every' and 'any' file patterns"

inputs:
  every_filter:
    description: "Patterns where every file must match (in YAML array format)"
    required: true
  any_filter:
    description: "Patterns where any file can match (in YAML array format)"
    required: true

outputs:
  every_changed:
    description: "True if all files in 'every_filter' have changed"
    value: ${{ steps.filter_every.outputs.every }}
  any_changed:
    description: "True if any files in 'any_filter' have changed"
    value: ${{ steps.filter_any.outputs.any }}

runs:
  using: 'composite'
  steps:
    - name: Filter Every Patterns
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter_every
      if: inputs.every_filter != ''
      with:
        predicate-quantifier: 'every'
        filters: |
          every:
          ${{ inputs.every_filter }}

    - name: Filter Any Patterns
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter_any
      if: inputs.any_filter != ''
      with:
        predicate-quantifier: 'some'
        filters: |
          any:
          ${{ inputs.any_filter }}
