name: "Build and Publish Chainlink"

on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop
      - "release/**"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      git_ref:
        description: "The git ref to check out"
        required: true

env:
  GIT_REF: ${{ github.event.inputs.git_ref || github.ref }}

concurrency:
  group: ${{ github.ref }}-${{ github.repository }}-${{ github.event_name }}--e2e-tests-${{ inputs.distinct_run_name }}
  cancel-in-progress: true

jobs:
  goreleaser-build-publish-chainlink:
    name: "goreleaser-build-publish-${{ matrix.image-name }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: chainlink
            goreleaser-config: .goreleaser.develop.yaml
          - image-name: ccip
            goreleaser-config: .goreleaser.ccip.develop.yaml
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ env.GIT_REF }}

      - name: Get Chainlink Image Tag
        id: chainlink-image-tag
        uses: ./.github/actions/get-chainlink-image-tag

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_BUILD_PUBLISH_DEVELOP_PR }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
          role-session-name: goreleaser-build-publish-${{ matrix.image-name }}

      - name: Build and publish images
        uses: ./.github/actions/goreleaser-build-sign-publish
        with:
          enable-docker-publish: true
          docker-registry: ${{ secrets.AWS_SDLC_ECR_HOSTNAME }}
          docker-image-name: ${{ matrix.image-name }}
          docker-image-tag: ${{ steps.chainlink-image-tag.outputs.base-image-tag }}
          enable-goreleaser-snapshot: "true"
          goreleaser-exec: ./tools/bin/goreleaser_wrapper
          goreleaser-config: ${{ matrix.goreleaser-config }}
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
          zig-version: 0.11.0

      - name: Output image name and digest
        id: get-image-name-digest
        shell: bash
        run: |
          artifact_path="dist/artifacts.json"
          jq -r '.[] | select(.type == "Docker Image") | "\(.name)"' ${artifact_path} >> output.txt

          echo "## Published ${{ matrix.image-name }} Images" | tee -a "$GITHUB_STEP_SUMMARY"
          while read -r line; do
            echo "* $line" | tee -a "$GITHUB_STEP_SUMMARY"
          done < output.txt
  

      - name: Collect Metrics
        if: always()
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
        with:
          id: goreleaser-build-publish
          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          this-job-name: goreleaser-build-publish-${{ matrix.image-name }}
        continue-on-error: true