name: LLM Action Error Reporter
on:
  workflow_run:
    workflows: ["CI Core"] # This workflow will be triggered as soon as one of worfklows is completed
    types:
      - completed

jobs:
  analyze_logs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
      actions: read
    steps:
      - name: Analyze logs
        # TODO: change to released version when avail.
        uses: smartcontractkit/.github/actions/llm-action-error-reporter@d84490e5ecdc1ec421d61fd985c8f08d5d6fca61 # re-3088/reduce-comment-noise
        with:
          parent-workflow-conclusion: ${{ github.event.workflow_run.conclusion }}
          pr-comment-generate-success-report: false
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          openai-model: "gpt-4-turbo-2024-04-09"
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
