name: On Demand VRFV2 Plus Smoke Tests
on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: "Test Suite to run"
        required: true
        type: choice
        default: "All Tests"
        options:
          - "All Tests"
          - "Selected Tests"
      test_list_regex:
        description: "Regex for 'Selected Tests' to run"
        required: false
        default: "TestVRFv2Plus$/(Link_Billing|Native_Billing|Direct_Funding)|TestVRFV2PlusWithBHS"
      test_config_override_path:
        description: Path to a test config file used to override the default test config
        required: false
        type: string          
      test_secrets_override_key:
        description: 'Key to run tests with custom test secrets'
        required: false
        type: string
      chainlink_version:
        description: Chainlink image version to use
        default: develop
        required: false
        type: string            
        
jobs:
  run-e2e-tests-workflow:
    name: Run E2E Tests
    uses: ./.github/workflows/run-e2e-tests-reusable-workflow.yml
    with:
      custom_test_list_json: >
        {
          "tests": [
            {
              "id": "TestVRFv2Plus",
              "path": "integration-tests/smoke/vrfv2plus_test.go",
              "runs_on": "ubuntu-latest",
              "test_env_type": "docker",
              "test_cmd": "cd integration-tests/smoke && go test vrfv2plus_test.go -test.parallel=1 -timeout 3h -count=1 -json -v"
            }
          ]
        }      
      chainlink_version: ${{ inputs.chainlink_version }}
    secrets:
      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
      QA_PYROSCOPE_INSTANCE: ${{ secrets.QA_PYROSCOPE_INSTANCE }}
      QA_PYROSCOPE_KEY: ${{ secrets.QA_PYROSCOPE_KEY }}
      QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
      GRAFANA_INTERNAL_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
      GRAFANA_INTERNAL_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
      GRAFANA_INTERNAL_HOST: ${{ secrets.GRAFANA_INTERNAL_HOST }}
      GRAFANA_INTERNAL_URL_SHORTENER_TOKEN: ${{ secrets.GRAFANA_INTERNAL_URL_SHORTENER_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN }}
      AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}        
      TEST_SECRETS_OVERRIDE_BASE64: ${{ secrets[inputs.test_secrets_override_key] }}
