name: Run VRF E2E Release Tests

on:
  workflow_dispatch:
    inputs:
      chainlink_version:
        description: Chainlink image version to use
        default: develop
        required: true
        type: string
  push:

jobs:
  run-e2e-tests-workflow:
    name: Run E2E Tests
    uses: ./.github/workflows/run-e2e-tests-reusable-workflow.yml
    with:
      chainlink_version: ${{ github.event.inputs.chainlink_version }}
      # test_workflow: VRF E2E Release Tests
      test_ids: 'smoke/vrfv2plus_test.go:*'
      slack_notification_after_tests: true
      # slack_notification_after_tests_channel_id: "#team-test-tooling-internal"
      slack_notification_after_tests_channel_id: "#lf-slack-notification-tests"
      slack_notification_after_tests_name: JUST TESTING PLEASE IGNORE - VRF E2E Release Tests
      slack_notification_after_tests_notify_user_id_on_failure: 'D04ENK9VDFA'
    secrets:
      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
      QA_PYROSCOPE_INSTANCE: ${{ secrets.QA_PYROSCOPE_INSTANCE }}
      QA_PYROSCOPE_KEY: ${{ secrets.QA_PYROSCOPE_KEY }}
      QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
      GRAFANA_INTERNAL_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
      GRAFANA_INTERNAL_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
      GRAFANA_INTERNAL_HOST: ${{ secrets.GRAFANA_INTERNAL_HOST }}
      GRAFANA_INTERNAL_URL_SHORTENER_TOKEN: ${{ secrets.GRAFANA_INTERNAL_URL_SHORTENER_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN }}
      AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}    
      SLACK_BOT_TOKEN: ${{ secrets.QA_SLACK_API_KEY }}
